
bug:
  - any: ['testfile.txt']

test:
  - 'testfile.txt'

# repo:
  #- ./*

# static:
  #- ./static/*

# Add 'label1' to any changes within 'example' folder or any subfolders
#label1:
 # - ./**/*

# Add 'label2' to any file changes within 'example2' folder
# label2: ./*
